apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-proxy.fullname" . }}
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.proxy.config | b64enc | quote }}
