apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-proxy.fullname" . }}-http
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ssh-proxy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh-proxy.fullname" . }}-ssh
  labels:
    {{- include "ssh-proxy.labels" . | nindent 4 }}
    {{- with .Values.ssh.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ssh.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ssh.service.type }}
  {{- with .Values.ssh.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.ssh.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.ssh.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ssh.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  ports:
    - port: {{ .Values.ssh.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh-proxy.selectorLabels" . | nindent 4 }}
